CREATE TABLE commission_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    size_preference VARCHAR(255) NULL,
    budget_note TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NULL,
    CONSTRAINT pk_commission_requests PRIMARY KEY (id),
    CONSTRAINT fk_commission_requests_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT chk_commission_requests_status CHECK (status IN ('NEW', 'IN_REVIEW', 'ACCEPTED', 'DECLINED', 'COMPLETED'))
);

CREATE INDEX idx_commission_requests_email ON commission_requests(email);
CREATE INDEX idx_commission_requests_status ON commission_requests(status);
