-- Dodavanje polja za URL slike u tablicu products
ALTER TABLE products ADD COLUMN image_url VARCHAR(500);

-- Tablica za narudžbe
CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NULL,
                        customer_name VARCHAR(100) NOT NULL,
                        customer_email VARCHAR(100) NOT NULL,
                        shipping_address VARCHAR(255) NOT NULL,
                        city VARCHAR(100) NOT NULL,
                        postal_code VARCHAR(20) NOT NULL,
                        total_amount DECIMAL(10, 2) NOT NULL,
                        status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Tablica za stavke narudžbe
CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             quantity INT NOT NULL DEFAULT 1,
                             price DECIMAL(10, 2) NOT NULL,
                             CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
                             CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id)
);